package com.hsicen.coroutineimport kotlinx.coroutines.MainScopeimport kotlinx.coroutines.asyncimport kotlinx.coroutines.launchimport kotlinx.coroutines.supervisorScope/** * 作者：hsicen  9/22/21 08:55 * 邮箱：codinghuang@163.com * 作用： * 描述：协程异常测试 */fun main() {  MainScope().launch {    supervisorScope {      val job1 = async {        throw Exception("Test exception.")      }      kotlin.runCatching {        job1.await()      }.onSuccess {        println("Job success")      }.onFailure {        println("Job failure: ${it.message}")      }    }  }}